apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rc1u4og97-nodejs
  janus-idp.io/tekton: rc1u4og97-nodejs
  backstage.io/kubernetes-id: rc1u4og97-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rc1u4og97-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
